import sqlite3

conn=sqlite3.connect("application.db")
print("Database open successfully")
obj=conn.execute(
  #   "CREATE TABLE  USER (ID INTEGER PRIMARY KEY AUTOINCREMENT,USERNAME TEXT NOT NULL,USERMAIL TEXT  UNIQUE NOT NULL,FIRSTNAME TEXT NOT NULL,SECONDNAME TEXT NOT NULL,CONTACT INTEGER UNIQUE NOT NULL,DOB DATE NOT NULL,CITY TEXT NOT NULL,GENDER TEXT NOT NULL,AGE INTEGER NOT NULL,PASSWORD TEXT UNIQUE NOT NULL)"

    # "CREATE TABLE  POST(POSTID INTEGER PRIMARY KEY AUTOINCREMENT,PTIME DATETIME DEFAULT CURRENT_TIMESTAMP,NAME TEXT NOT NULL,MESSAGE TEXT,IMAGE TEXT)"

# "CREATE TABLE  ISSUE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT NOT NULL,QUERY TEXT NOT NULL)"


)

print("Table Created Successfully ")